# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: unoGameTestsAndDeployment

on:
  push: 

jobs:
  runUnitIntegrationTests:

    runs-on: ubuntu-latest
    strategy:
      matrix: 
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: checkout the code
      - uses: actions/checkout@v4

      - name: Set up Python 3.10 with matrix
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version}}
          
      - name: Install dependencies-ruff linter
        run: |
          pip install ruff
          ruff check .
      - name: Install dependencies-coverage
        run: |
          pip install coverage

      - name: Test with unittest
        run: |
          coverage run --omit=tests.py tests.py -b
          coverage rport >> coverage_report.txt
          
