name: unoGameTestsAndDeployment

on:
  push: 

jobs:
  runUnitIntegrationTests:

    runs-on: ubuntu-latest
    strategy:
      matrix: 
        python-version: ["3.10"]

    steps:
      - name: checkout the code
        uses: actions/checkout@v3

      - name: Set up Python 3.10 with matrix
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version}}
          
      - name: Install dependencies-ruff linter
        run: |
          pip install ruff
          ruff check . --fix
      - name: Install dependencies-coverage
        run: |
          pip install coverage

      - name: Test with unittest
        run: |
          coverage run --omit=tests.py tests.py -b
          coverage report
      
  pushToDockerRegistry:
    runs-on: ubuntu-latest
    needs: runUnitIntegrationTests

    steps:
      - name: Login into DockerHub 
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: build and push a Docker image to DockerHub 
        uses: docker/build-push-action@v4
        with: 
          context: ./DockerFolder
          file: ./DockerFolder/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cs333-uno-game:latest
      

          
